# Start with a base image containing Python 3.11
FROM python:3.11

# Create app directory
WORKDIR /

# Install dependencies
COPY requirements.txt .
RUN apt-get update && apt-get upgrade -y && \
    apt-get install -y libpq-dev postgresql-client nginx build-essential supervisor && \
    pip install --upgrade pip && \
    pip install -r requirements.txt && \
    pip install gunicorn

# Copy project
COPY . .

# Configure nginx
RUN rm -f /etc/nginx/sites-enabled/default && \
    rm -f /etc/nginx/sites-available/default && \
    rm -f /etc/nginx/conf.d/default.conf && \
    rm -f /etc/nginx/nginx.conf
COPY nginx.conf /etc/nginx/nginx.conf

# Create static directory and set permissions
RUN mkdir -p /apps/static && \
    python manage.py collectstatic --noinput && \
    chown -R www-data:www-data /apps/static

# Expose ports
EXPOSE 80

# Define environment variables
ENV POSTGRES_USER=unsql_admin \
    POSTGRES_PASSWORD=OZpb3Bf4zoTslo \
    POSTGRES_DB=postgres \
    POSTGRES_HOST=unsql-postgres.postgres.database.azure.com \
    ASSETS_ROOT=/static/assets \
    AUTH0_CLIENT_ID=zLNRmKVMfqEbkcqrD7SPAupBYtdD5MEJ \
    AUTH0_CLIENT_SECRET=4LRjSrJkT-LG28o2YwQvia4SpaEQzeYIS6U9-x2I_CPedflhfcES0ITvAAWy2wRQ \
    AUTH0_DOMAIN=auth.unsql.ai \
    AUTH0_MACHINE_ID=wD0m9PYYAg5OvcU0kV1dgngbJYhH7V8v \
    AUTH0_MACHINE_DOMAIN=auth.unsql.ai \
    AUTH0_MACHINE_SECRET=x5ar2VCJgKrOEZVnk_iDKA3Y-tPKgcowuGAT_bNhXqmHkB_0yUUlhPOgw1u2W3nD \
    AUDIENCE=https://auth.unsql.ai/api/v2/ \
    STRIPE_PUBLISHABLE_KEY=pk_test_xFLF8rLaykv0tiGXFkhMj5XF \
    STRIPE_SECRET_KEY=sk_test_duuyOcc0Ja7Q92P7O776rm5O \
    STRIPE_ENDPOINT_SECRET=whsec_d48ec9a51008e7d6ae6ee5d2c56c5fad278a8f7a70e43efbdbce3d0d4fd9b8bf \
    RETELL_API_KEY=key_1d9675e6bf846f5fa1fbd18fd3f7 \
    STRIPE_PRODUCT_SOLO=prod_RFHFbwepKR3vwa \
    STRIPE_PRICE_SOLO=price_1QMmh4HnPOZkGCSZfkoC1Jlq \
    WHATSAPP_TOKEN=your_whatsapp_business_api_token \
    # OPENAI_API_KEY=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 \
    OPENAI_API_KEY= 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 \
    FERNET_KEY=7fVsiG6U_isOUpu4ccVRuaOxLhYvCxkU4Sg4wMILRG0= \
    DJANGO_SETTINGS_MODULE=core.settings.production

CMD ["sh", "-c", "\
    until PGPASSWORD=$POSTGRES_PASSWORD psql -h $POSTGRES_HOST -U $POSTGRES_USER -d $POSTGRES_DB -p 5432 -c '\\q'; do \
      >&2 echo 'Postgres is unavailable - sleeping'; \
      sleep 1; \
    done; \
    >&2 echo 'Postgres is up - executing command'; \
    python manage.py collectstatic --no-input; \
    python manage.py makemigrations; \
    python manage.py makemigrations accounts; \
    python manage.py makemigrations authentication; \
    python manage.py makemigrations home; \
    python manage.py migrate; \
    gunicorn -c ./gunicorn-cfg.py core.wsgi:application & \
    nginx -g 'daemon off;' || (echo 'Nginx failed to start' && cat /var/log/nginx/error.log); \
"]
