# Generated by Django 3.2.13 on 2023-07-05 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auth0User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('auth0_id', models.CharField(max_length=200)),
                ('stripe_customer_id', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=10000)),
                ('slug', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=10000)),
                ('sql', models.CharField(max_length=10000, null=True)),
                ('head_data', models.CharField(max_length=10000, null=True)),
                ('system_message', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.IntegerField(default=0)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.chat')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.auth0user')),
            ],
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('db_name', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('password', models.BinaryField()),
                ('host', models.CharField(max_length=200)),
                ('port', models.IntegerField()),
                ('users_id', models.IntegerField()),
                ('db_type', models.CharField(choices=[('postgres', 'PostgreSQL'), ('mysql', 'MySQL'), ('mssql', 'Microsoft SQL Server'), ('oracle', 'Oracle'), ('sqlite', 'SQLite')], max_length=200)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.auth0user')),
            ],
        ),
        migrations.AddField(
            model_name='chat',
            name='connection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.connection'),
        ),
        migrations.AddField(
            model_name='chat',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.auth0user'),
        ),
    ]
