# Generated by Django 3.2.13 on 2023-07-05 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='asdf',
            field=models.CharField(default='hello', max_length=200),
        ),
    ]
