# Generated by Django 3.2.13 on 2023-07-05 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_connection_asdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connection',
            name='asdf',
        ),
    ]
