# Generated by Django 3.2.13 on 2023-07-05 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_connection_asdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='db_type',
            field=models.CharField(choices=[('postgres', 'PostgreSQL'), ('mysql', 'MySQL'), ('mssql', 'Microsoft SQL Server'), ('oracle', 'Oracle'), ('sqlite', 'SQLite'), ('none', 'None')], default='none', max_length=200),
        ),
    ]
