# Generated by Django 3.2.13 on 2025-06-25 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_sync_users'),
        ('home', '0007_merge_20250114_sync_users'),
    ]

    operations = [
    ]
