#enable this for docker-compose
upstream webapp {
    server web:5005;
}

server {
    listen 80;
    server_name localhost;

    location /static/ {
        #alias /apps/apps/static/;
        alias /apps/static/;
    }

    location / {
        proxy_pass http://webapp;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

}